### ISSUE TITLE
Readme and Code detail

### ISSUE THREAD

**Issue by bitolwastaken** [njlochner/haskell_turing_machine#1]
The readme and code is far too detailed and well written. The syntax makes following this code not challenging at all, thus spoiling the fun one normally has on github which is to decipher the code. The readme reads like an instruction book from ikea, but is concisely written providing no ambiguity and also destroys the creative process with it's "facts". I have grown to resent these projects as they deprive me of my right to free thought and hinder the ability of other like-minded, creative individuals from our freedom from said harmful "facts". I hereby mark this project as an issue, and wish to see it's immediate rewrite in a more logical manner, perhaps in another language, perhaps in Russian or something.

**Comment by nicholelochner** [comment]
Closed issue as joke from friend.
